# Generated by Django 3.2 on 2022-01-06 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Категорія події')),
            ],
            options={
                'verbose_name': 'Категорія події',
                'verbose_name_plural': 'Категорія події',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Тергромада',
                'verbose_name_plural': 'Тергромада',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FireType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Тип події')),
            ],
            options={
                'verbose_name': 'Тип події',
                'verbose_name_plural': 'Тип події',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='NoFire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_departure', models.IntegerField(default=0, null=True, verbose_name='Порядковий номер виїзду на добу')),
                ('date_of_receipt_message', models.DateTimeField(null=True, verbose_name='Дата|Час')),
                ('information', models.CharField(max_length=1000, verbose_name='Інформація про подію')),
                ('subdivisions', models.CharField(max_length=1000, verbose_name='Підрозділ')),
                ('departure_date', models.TimeField(null=True, verbose_name='час виїзду')),
                ('time_of_arrival_to_the_place', models.TimeField(default='00:00', null=True, verbose_name='час прибуття до місця')),
                ('time_return_to_location', models.TimeField(default='00:00', null=True, verbose_name='час повернення до місця розташування')),
                ('add_user', models.CharField(default=0, max_length=20, verbose_name='Хто додав')),
                ('edit_user', models.CharField(default='Не редагувалось', max_length=20, verbose_name='Хто відредагував')),
            ],
            options={
                'verbose_name': "Не пов'язані з пожежею",
                'verbose_name_plural': "Не пов'язані з пожежею",
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Район',
                'verbose_name_plural': 'Ройон',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.city')),
            ],
            options={
                'verbose_name': 'Населений пункт',
                'verbose_name_plural': 'Населені пункти',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Subtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.firetype')),
            ],
            options={
                'verbose_name': 'Підтип події',
                'verbose_name_plural': 'Підтип події',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_departure', models.IntegerField(default=0, null=True, verbose_name='Порядковий номер виїзду на добу')),
                ('date_of_receipt_message', models.DateTimeField(null=True, verbose_name='Дата|Час')),
                ('information', models.CharField(max_length=2000, verbose_name='Інформація про подію')),
                ('subdivisions', models.CharField(max_length=2000, verbose_name='Підрозділ')),
                ('quantity_peoples', models.IntegerField(default=0, null=True, verbose_name='Кількість о.с')),
                ('quantity_technics', models.IntegerField(default=0, null=True, verbose_name='Кількість од.тex.')),
                ('quantity_rescued', models.IntegerField(default=0, null=True, verbose_name='Кількість врятованих')),
                ('quantity_victims', models.IntegerField(default=0, null=True, verbose_name='Кількість постраждалих')),
                ('quantity_dead', models.IntegerField(default=0, null=True, verbose_name='Кількість загиблих')),
                ('quantity_rescued_kids', models.IntegerField(default=0, null=True, verbose_name='Дітей')),
                ('quantity_victims_kids', models.IntegerField(default=0, null=True, verbose_name='Дітей')),
                ('quantity_dead_kids', models.IntegerField(default=0, null=True, verbose_name='Дітей')),
                ('quantity_ammunition', models.IntegerField(default=0, null=True, verbose_name='')),
                ('violated_conditions', models.IntegerField(default=0, null=True, verbose_name='')),
                ('quantity_objects', models.IntegerField(default=0, null=True, verbose_name='')),
                ('departure_date', models.TimeField(default='00:00', null=True, verbose_name='час виїзду')),
                ('time_of_arrival_to_the_place', models.TimeField(default='00:00', null=True, verbose_name='час прибуття до місця')),
                ('barrel_feed_time', models.TimeField(default='00:00', null=True, verbose_name='час подачі першого ствола на гасіння')),
                ('area', models.FloatField(default=0, null=True, verbose_name='площа пожежі(м2)')),
                ('localization_time', models.TimeField(default='00:00', null=True, verbose_name='час локалізації')),
                ('area2', models.FloatField(default=0, null=True, verbose_name='площа пожежі(м2)')),
                ('liquidation', models.BooleanField(default=False, verbose_name='Ліквідовано')),
                ('liquidation_time', models.TimeField(default='00:00', null=True, verbose_name='час ліквідації')),
                ('time_return_to_location', models.TimeField(default='00:00', null=True, verbose_name='час повернення до місця розташування')),
                ('add_user', models.CharField(default=0, max_length=20, verbose_name='Хто додав')),
                ('edit_user', models.CharField(default='Не редагувалось', max_length=20, verbose_name='Хто відредагував')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='journal.category', verbose_name='Категорія')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='journal.city')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='journal.region')),
                ('subtype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='journal.subtype', verbose_name='Підтип')),
                ('town', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='journal.town')),
                ('type_of_fire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='journal.firetype', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Журналу виїзду',
                'verbose_name_plural': 'Журнал виїзду',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.region'),
        ),
    ]
