# Generated by Django 3.2 on 2022-01-06 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subdivisions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Підрозділ')),
            ],
            options={
                'verbose_name': 'Підрозділ',
                'verbose_name_plural': 'Підрозділи',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('number_of_calls', models.IntegerField(default=0, verbose_name='Кількість дзвінків')),
                ('add_user', models.CharField(max_length=100, null=True, verbose_name='Додав')),
                ('subdivisions', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='statistic.subdivisions', verbose_name='Підрозділ')),
            ],
            options={
                'verbose_name': 'Статистику',
                'verbose_name_plural': 'Статистика',
                'ordering': ['-date'],
            },
        ),
    ]
