from django.urls import path
from .views import *

urlpatterns = [
    path('', OperativeJournal.as_view(), name='journal'),
    path('add/', add_journal, name='add_journal'),
    path('edit/<int:id>/', edit_journal, name='edit_journal'),
    path('del/<int:id>/', del_journal, name='del_journal'),
    path('filter/', filter_date_range, name='filter'),
    path('statistic/', StatisticJournal.as_view(), name='statistic_journal'),
    path('statistic/filter/', filter, name='filter_journal'),
    path('statistic/page1/', StatisticJournal1.as_view(), name='statistic_journal_page1'),
    path('statistic/page2/', StatisticJournal2.as_view(), name='statistic_journal_page2'),
    path('statistic/page3/', StatisticJournal3.as_view(), name='statistic_journal_page3'),
    path('non_fire/', JournalNotFire.as_view(), name='non_fire'),
    path('non_fire/edit/<int:id>/', edit_non_fire, name='edit_non_fire'),
    path('non_fire/add/', add_no_fire, name='add_no_fire'),
    path('non_fire/del/<int:id>/', del_non_fire, name='del_no_fire'),
    path('non_fire/page1/', JournalNotFire1.as_view(), name='non_fire_page1'),
    path('non_fire/page2/', JournalNotFire2.as_view(), name='non_fire_page2'),
    path('non_fire/page3/', JournalNotFire3.as_view(), name='non_fire_page3'),
    path('non_fire/page1/edit/<int:id>/', edit_non_fire, name='edit_non_fire_page1'),
    path('non_fire/page2/edit/<int:id>/', edit_non_fire, name='edit_non_fire_page2'),
    path('non_fire/page3/edit/<int:id>/', edit_non_fire, name='edit_non_fire_page3'),
    path('non_fire/page1/del/<int:id>/', del_non_fire, name='del_non_fire_page1'),
    path('non_fire/page2/del/<int:id>/', del_non_fire, name='del_non_fire_page2'),
    path('non_fire/page3/del/<int:id>/', del_non_fire, name='del_non_fire_page3'),
    path('page1/', OperativeJournal1.as_view(), name='page1'),
    path('page2/', OperativeJournal2.as_view(), name='page2'),
    path('page3/', OperativeJournal3.as_view(), name='page3'),
    path('page1/edit/<int:id>/', edit_journal, name='edit_journal_page1'),
    path('page2/edit/<int:id>/', edit_journal, name='edit_journal_page2'),
    path('page3/edit/<int:id>/', edit_journal, name='edit_journal_page3'),
    path('page1/del/<int:id>/', del_journal, name='del_journal_page1'),
    path('page2/del/<int:id>/', del_journal, name='del_journal_page2'),
    path('page3/del/<int:id>/', del_journal, name='del_journal_page3'),
    path('ajax/load-cities/', load_cities, name='ajax_load_cities'),
    path('ajax/load-cities/town/', load_cities_town, name='ajax_load_cities_town'),
    path('ajax/load-subtype/subtype/', load_subtype, name='ajax_load_subtype'),

]
